version: '3'
services:
  corda-local-network:
    image: corda-local-network
    ports:
    - "1114:1114"
    - "10000-10200:10000-10200"
  corda-transaction-builder:
      image: corda-transaction-builder:alpha
      ports:
      - "1112:1112"
  service-bus-listener:
    image: service-bus-listener:alpha
    ports:
    - "1113:1113"


